feat: husky commitlint

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,9 +1,10 @@
-commit_msg_file=$1
-commit_msg=$(cat $commit_msg_file)
+# commit_msg_file=$1
+# commit_msg=$(cat $commit_msg_file)
 
-pattern="^(feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?: .{1,50}"
+# pattern="^(feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?: .{1,50}"
 
-if ! echo "$commit_msg" | grep -qE "$pattern"; then
-  echo "Error: Commit message does not match Conventional Commits pattern."
-  exit 1
-fi
+# if ! echo "$commit_msg" | grep -qE "$pattern"; then
+#   echo "Error: Commit message does not match Conventional Commits pattern."
+#   exit 1
+# fi
+pnpm exec commitlint --edit $1
